SET SCHEMA FN4MI0700044;

CREATE OR REPLACE FUNCTION F_GET_ALL_APPLIANCES(P_PHONE_NUMBER CHAR(10))
RETURNS TABLE(NAME VARCHAR(100), MODEL VARCHAR(20), DATE_OF_REPAIR DATE, TECHNICIAN_NAME VARCHAR(100))
RETURN
    SELECT A.NAME, A.MODEL, R.DATE, T.NAME
    FROM APPLIANCE A, REPAIR R, TECHNICIAN T
    WHERE A.CUSTOMER_PHONE_NUMBER = P_PHONE_NUMBER
    AND A.APPLIANCE_ID = R.APPLIANCE_ID
    AND R.TECHNICIAN_ID = T.TECHNICIAN_ID;

SELECT *
FROM TABLE(FN4MI0700044.F_GET_ALL_APPLIANCES('0899000112')) T;

CREATE OR REPLACE FUNCTION F_AVG_PRICE_FOR_CATEGORY (P_CATEGORY VARCHAR(50))
RETURNS INT
BEGIN
    DECLARE P_AVG_PRICE DECIMAL(9, 2);

    SELECT AVG(PRICE) INTO P_AVG_PRICE
    FROM REPAIR
    WHERE APPLIANCE_ID IN ( SELECT APPLIANCE_ID
                            FROM APPLIANCE
                            WHERE APPLIANCE_CATEGORY = P_CATEGORY);

    RETURN P_AVG_PRICE;
END;

VALUES FN4MI0700044.F_AVG_PRICE_FOR_CATEGORY('TV');

