SET SCHEMA FN4MI0700044;

CREATE TABLE REPAIR_PRICE_INCREASE_LOG (
    APPLIANCE_ID INT NOT NULL,
    TECHNICIAN_ID INT NOT NULL,
    OLD_PRICE DECIMAL(9, 2) NOT NULL,
    NEW_PRICE DECIMAL(9, 2) NOT NULL
);

CREATE OR REPLACE TRIGGER TRIG_AFTER_UPDATE_REPAIR_PRICE
AFTER UPDATE OF PRICE ON REPAIR
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
WHEN (N.PRICE > O.PRICE)
    INSERT INTO REPAIR_PRICE_INCREASE_LOG(APPLIANCE_ID, TECHNICIAN_ID, OLD_PRICE, NEW_PRICE)
    VALUES (N.APPLIANCE_ID, N.TECHNICIAN_ID, O.PRICE, N.PRICE);

UPDATE REPAIR
SET PRICE = PRICE + 50
WHERE APPLIANCE_ID = 280;

UPDATE REPAIR
SET PRICE = PRICE - 50
WHERE APPLIANCE_ID = 290;

SELECT * FROM REPAIR_PRICE_INCREASE_LOG;


CREATE OR REPLACE TRIGGER TRIG_AFTER_INSERT_TECHNICIAN
AFTER INSERT ON TECHNICIAN
REFERENCING NEW AS N
FOR EACH ROW
BEGIN
  DECLARE V_TECHNICIAN_ID INT;

  SET V_TECHNICIAN_ID = N.TECHNICIAN_ID;
  CALL FN4MI0700044.P_TECHNICIAN_INFO(V_TECHNICIAN_ID);
END;

INSERT INTO TECHNICIAN(NAME, EGN, TECHNICIAN_CATEGORY)
VALUES ('John Doe', 6598127643, 'Washing machine');