SET SCHEMA FN4MI0700044;

CREATE VIEW TECHNICIAN_INFO (TECHNICIAN_NAME, TECHNICIAN_AGE, CATEGORY, AVG_SALARY)
AS
SELECT T.NAME, EXTRACT(YEAR FROM CURRENT_DATE) - CAST(CONCAT('19', SUBSTR(T.EGN, 1, 2)) AS INT) AS , T.TECHNICIAN_CATEGORY,
       FN4MI0700044.F_AVG_PRICE_FOR_CATEGORY(T.TECHNICIAN_CATEGORY)
FROM TECHNICIAN T;

SELECT * FROM TECHNICIAN_INFO;

CREATE VIEW V_CUSTOMER_APPLIANCE_INFO (CUSTOMER_NAME, PHONE_NUMBER, APPLIANCE_NAME, APPLIANCE_CATEGORY, APPLIANCE_ID)
AS
SELECT C.NAME as CUSTOMER_NAME, C.PHONE_NUMBER, A.NAME as APPLIANCE_NAME, A.APPLIANCE_CATEGORY, A.APPLIANCE_ID
FROM CUSTOMER C, APPLIANCE A
WHERE C.PHONE_NUMBER = A.CUSTOMER_PHONE_NUMBER;

SELECT *
FROM V_CUSTOMER_APPLIANCE_INFO
WHERE APPLIANCE_CATEGORY = 'Oven';

